{% set name = "qiskit-ibmq-provider" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-ibmq-provider-{{ version }}.tar.gz
  sha256: 758938ce13a09f53ada9f4852891d7ca7ba98fddab6b9850417bbcb0efc26c2e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - dataclasses >=0.8
    - numpy <1.24
    - python >=3.7
    - python-dateutil >=2.8.0
    - qiskit-terra >=0.18.0
    - requests >=2.19
    - requests_ntlm >=1.1.0
    - urllib3 >=1.21.1
    - websocket-client <=1.3.3
    - websockets >=10.0

test:
  imports:
    - qiskit.providers.ibmq
    - qiskit.providers.ibmq.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/qiskit-ibmq-provider
  summary: Qiskit provider for accessing the quantum devices and simulators at IBMQ
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
