{% set name = "qiskit-ibmq-provider" %}
{% set version = "0.20.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-ibmq-provider-{{ version }}.tar.gz
  sha256: a74299c2e17370ec43040dda6b4097c25be9fc42fb51c9923232a2279dd36fc0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - dataclasses >=0.8,<1.dev0
    - numpy <1.24
    - python >=3.7
    - python-dateutil >=2.8.0,<2.9.dev0
    - qiskit-terra >=0.23.0,<0.24.dev0
    - requests >=2.28.0,<2.29.dev0
    - requests_ntlm >=1.1.0,<1.2.dev0
    - urllib3 >=1.26.0,<1.27.dev0
    - websocket-client >=1.5.1,<1.6.dev0
    - websockets >=10.0

test:
  imports:
    - qiskit.providers.ibmq
    - qiskit.providers.ibmq.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/qiskit-ibmq-provider
  summary: Qiskit provider for accessing the quantum devices and simulators at IBMQ
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
